### ISSUE TITLE
Steering Axis Issue

### ISSUE THREAD

**Issue by RapidKebab** [nothke/shakedown-docs#2]
- Small oversight: the steering axis is directly tied to the world up axis or so it seems, so the wheels effectively slowly invert steering as the car flips. 

- Not only does the steering direction/amount change but the wheels also go from facing the bottom of the car to being upright as one steers, best visible on a half-flipped car, where this will cause them to lean at an odd angle to the side.

**Comment by nothke** [comment]
I've noticed this myself, haha. I just never tested rotations in the car that is not flat on the ground while developing. I'm probably adding rotations in the wrong order, as there is a roll, steering and also 180 rotation for right side wheels. Note that the wheel model rotation is purely visual, so it doesn't influence physics. The graphical wheel follows physics.  Will fix.

**Comment by nothke** [comment]
Rotations of wheels has been fixed now.
